import type {Metadata} from "next";
import {Poppins, Unbounded} from "next/font/google";
import React from "react";
import '@/styles/abstracts/index.scss';
import '@/styles/globals.scss';

const poppins = Poppins({
    subsets: ["latin"],
    variable: '--font-poppins',
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const unbounded = Unbounded({
    subsets: ["latin"],
    variable: '--font-unbounded',
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${poppins.variable} ${unbounded.variable}`}>{children}</body>
        </html>
    );
}
